<?php

// INCLUDE NOS DA UN WARNING SI NO EXISTE PERO SIGUE EJECUTANDO
// REQUIRE DA FATAL ERROR Y NO CONTINUA EJECUTANDO
// REQUIRE O INCLURE _ONCE EJECUTA UNA SOLA VEZ POR MAS QUE SE REPITA LA MIMSMA RUTA

include("forx.php");
require "for.php";
require "x.php";

?>